export const features = [
  'Dashboard',
  'Employee management',
  'Doctors',
  // 'Nurses',
  'Therapist',
  'Exercise Management',
  // 'Pharmacist',
  'Lab Technician',
  'Administrator',
  'FrontDesk',
  'Security',
  'OtherStaff',
  'Appointments',
  'Reports Management',
  'Disease-Management',
  'Therapy Management',
  // 'Exercise Management',
  'Program Management',
  'Package Management',

  'Tests',
  // 'Treatments',
  'Therapy Management',
  'Payouts',
  'Help',
  'Customer Management',
  'ConsentForms',
  'Vendor Management',
  // 'Pharmacy Management',
  'Push Notification',
  // 'Inventory Management',
  'Support',
  'Billing',
  'Analytics',
  'Tax reports',
  'Refered By Doctor',
  'Patient Management'
]

export const actions = ['create', 'read', 'update', 'delete']
